{
  pkgs,
  lib,
  ...
}: {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."pihole" = {
    image = "pihole/pihole:latest";
    environment = {
      "FTLCONF_dns_listeningMode" = "all";
      "FTLCONF_webserver_port" = "8080o,[::]:8080o,8443os,[::]:8443os";
      "TZ" = "Europe/Berlin";
    };
    environmentFiles = [
      "/var/lib/secrets/pihole-token.env"
    ];
    volumes = [
      "/data/pihole:/etc/pihole:rw"
    ];
    ports = [
      "53:53/tcp"
      "53:53/udp"
      "8080:80/tcp"
      "8443:443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--cap-add=SYS_NICE"
      "--cap-add=SYS_TIME"
      "--network=host"
    ];
  };
  systemd.services."docker-pihole" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-pihole-root.target"
    ];
    wantedBy = [
      "docker-compose-pihole-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-pihole-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };

  networking.firewall = {
    enable = true; # Already default, but explicit
    allowedTCPPorts = [53 8080 8443]; # DNS TCP, web UI HTTP, web UI HTTPS
    allowedUDPPorts = [53]; # DNS UDP (critical for most queries)
    # If you use Pi-hole's DHCP server feature, also add:
    # allowedUDPPorts = [ 53 67 ];       # DHCP server port
  };
}
