{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."zerobyte" = {
    image = "ghcr.io/nicotsx/zerobyte:v0.18";
    environment = {
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/var/lib/vaultwarden:/vaultwarden:rw"
      "/var/lib/zerobyte:/var/lib/zerobyte:rw"
    ];
    ports = [
      "4096:4096/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=SYS_ADMIN"
      "--device=/dev/fuse:/dev/fuse:rwm"
    ];
  };
  systemd.services."docker-zerobyte" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-zerobyte-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

  networking.firewall = {
    enable = true;
    allowedTCPPorts = [4096];
  };
}
